sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
branches:
  only:
  - pypi
install:
- pip install python-coveralls
script:
- coverage run -m unittest discover
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: sih4sing5hong5
  password:
    secure: EGwrnfOlCv3ULslBD6JgVZdOAqVegqrv9ZeDJIsBkRyxcWjLJYAksdA1GJ6s9CvZgB73CrAjM55fRjui2TTMgSLXbYuw56pKXVb+tfLSrZQeUl3b1LHylpuA+4hG3FoWpdMJo11ERHG1dbkBEOqU+2dL51FZh9eKsySAefDtsW8jbMiUvFUxc1vdnEmzrZ02zYQcYPdQjPxFEiYCK3xA2ZqwP2F3fvkoybtiiL3QkuzXjRLRojzXYXIxFCMSUCBtb3ctB37rBWPKe4qUezCr/QMMmFa3j64KjU2H+tm7a9RhWORKKOd1gOhvwZ2f/0q2n6uHsCsrcnlztHu1U2m325z1RRFzq5QI57wZNskdj855SYi427Vgl+7obJ2OlKCFJgHDbUGESA3XOHI41wEYKy6AMdFj0wqT3ZPyHUvRTrdhFGZE0rkUSboVWajLz1wDDu7DylMd3W4GnV1TwfUbz0qvSuzsmDZQ2WjdsWXoTh15PqCcgITw9MJE0eo3SRfseJtSrrqCrZx6bMGXFfrcUjRFdcbb++Crks+plp5e/hYLjQUIUcbcFst8uaZhJlPFIRmNaA75zjpqK/JD/XYRSLPQgNztl1CE8PpmcDi/rhb+CtiO+smU0GBkUUTsswKwW4YnTNnBgONwEn8bVSo9i0cWvAq8Nf8Z/7CK8VbSL/g=
  on:
    repo: sih4sing5hong5/Bleualign
    branch: pypi
